/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "test_service_constants.h"

namespace test_service {

const test_serviceConstants g_test_service_constants;

test_serviceConstants::test_serviceConstants() {
}

} // namespace

