/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef test_service_CONSTANTS_H
#define test_service_CONSTANTS_H

#include "test_service_types.h"

namespace test_service {

class test_serviceConstants {
 public:
  test_serviceConstants();

};

extern const test_serviceConstants g_test_service_constants;

} // namespace

#endif
